package com.example

import kotlin.test.Test
import kotlin.test.assertEquals

class DummyTests {
    @Test fun test1() = someAssertion()
    @Test fun test2() = someAssertion()
    @Test fun test3() = someAssertion()
    @Test fun test4() = someAssertion()
    @Test fun test5() = someAssertion()
    @Test fun test6() = someAssertion()
    @Test fun test7() = someAssertion()
    @Test fun test8() = someAssertion()
    @Test fun test9() = someAssertion()
    @Test fun test10() = someAssertion()
    @Test fun test11() = someAssertion()
    @Test fun test12() = someAssertion()
    @Test fun test13() = someAssertion()
    @Test fun test14() = someAssertion()
    @Test fun test15() = someAssertion()
    @Test fun test16() = someAssertion()
    @Test fun test17() = someAssertion()
    @Test fun test18() = someAssertion()
    @Test fun test19() = someAssertion()
    @Test fun test20() = someAssertion()
    @Test fun test21() = someAssertion()
    @Test fun test22() = someAssertion()
    @Test fun test23() = someAssertion()
    @Test fun test24() = someAssertion()
    @Test fun test25() = someAssertion()
    @Test fun test26() = someAssertion()
    @Test fun test27() = someAssertion()
    @Test fun test28() = someAssertion()
    @Test fun test29() = someAssertion()
    @Test fun test30() = someAssertion()
    @Test fun test31() = someAssertion()
    @Test fun test32() = someAssertion()
    @Test fun test33() = someAssertion()
    @Test fun test34() = someAssertion()
    @Test fun test35() = someAssertion()
    @Test fun test36() = someAssertion()
    @Test fun test37() = someAssertion()
    @Test fun test38() = someAssertion()
    @Test fun test39() = someAssertion()
    @Test fun test40() = someAssertion()
    @Test fun test41() = someAssertion()
    @Test fun test42() = someAssertion()
    @Test fun test43() = someAssertion()
    @Test fun test44() = someAssertion()
    @Test fun test45() = someAssertion()
    @Test fun test46() = someAssertion()
    @Test fun test47() = someAssertion()
    @Test fun test48() = someAssertion()
    @Test fun test49() = someAssertion()
    @Test fun test50() = someAssertion()
    @Test fun test51() = someAssertion()
    @Test fun test52() = someAssertion()
    @Test fun test53() = someAssertion()
    @Test fun test54() = someAssertion()
    @Test fun test55() = someAssertion()
    @Test fun test56() = someAssertion()
    @Test fun test57() = someAssertion()
    @Test fun test58() = someAssertion()
    @Test fun test59() = someAssertion()
    @Test fun test60() = someAssertion()
    @Test fun test61() = someAssertion()
    @Test fun test62() = someAssertion()
    @Test fun test63() = someAssertion()
    @Test fun test64() = someAssertion()
    @Test fun test65() = someAssertion()
    @Test fun test66() = someAssertion()
    @Test fun test67() = someAssertion()
    @Test fun test68() = someAssertion()
    @Test fun test69() = someAssertion()
    @Test fun test70() = someAssertion()
    @Test fun test71() = someAssertion()
    @Test fun test72() = someAssertion()
    @Test fun test73() = someAssertion()
    @Test fun test74() = someAssertion()
    @Test fun test75() = someAssertion()
    @Test fun test76() = someAssertion()
    @Test fun test77() = someAssertion()
    @Test fun test78() = someAssertion()
    @Test fun test79() = someAssertion()
    @Test fun test80() = someAssertion()
    @Test fun test81() = someAssertion()
    @Test fun test82() = someAssertion()
    @Test fun test83() = someAssertion()
    @Test fun test84() = someAssertion()
    @Test fun test85() = someAssertion()
    @Test fun test86() = someAssertion()
    @Test fun test87() = someAssertion()
    @Test fun test88() = someAssertion()
    @Test fun test89() = someAssertion()
    @Test fun test90() = someAssertion()
    @Test fun test91() = someAssertion()
    @Test fun test92() = someAssertion()
    @Test fun test93() = someAssertion()
    @Test fun test94() = someAssertion()
    @Test fun test95() = someAssertion()
    @Test fun test96() = someAssertion()
    @Test fun test97() = someAssertion()
    @Test fun test98() = someAssertion()
    @Test fun test99() = someAssertion()
    @Test fun test100() = someAssertion()

    private fun someAssertion() {
        assertEquals(1, 1)
        Thread.sleep(50)
    }
}
